name: Setup Node.js
description: Composite task to set up the Node.js environment used in CI

inputs:
  node-version:
    description: Version of Node.js
    required: true
  turbo-cache-key:
    description: The prefix for cache key for turbo or 'false' to disable caching
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # https://github.com/actions/virtual-environments/issues/1187
    - name: tune linux network
      shell: bash
      run: sudo ethtool -K eth0 tx off rx off
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      shell: bash
      run: pnpm install
    - name: Cache turbo
      if: inputs.turbo-cache-key != 'false'
      uses: actions/cache@v4
      with:
        path: ./.turbo/cache
        key: turbo2-cache-${{ inputs.turbo-cache-key }}-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo2-cache-${{ inputs.turbo-cache-key }}-${{ runner.os }}-
