kind: Service
apiVersion: v1

metadata:
  name: database-pg18

spec:
  ports:
  - name: psql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: database-pg18
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
