kind: Service
apiVersion: v1

metadata:
  name: web

spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
