name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-node:
    name: Build / Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    - name: Install latest npm
      run: |
        npm install --global npm@latest
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Cache turbo
      uses: actions/cache@v3
      with:
        path: ./node_modules/.cache/turbo
        key: turbo-cache-build-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-cache-build-${{ runner.os }}-
    - name: Run Build
      run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: npm
    - name: Install latest npm
      run: |
        npm install --global npm@latest
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Cache turbo
      uses: actions/cache@v3
      with:
        path: ./node_modules/.cache/turbo
        key: turbo-cache-lint-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-cache-lint-${{ runner.os }}-
    - name: Run Lint
      run: npm run lint

  build-docker:
    name: Build / Docker / ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ web, database-migration ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      uses: docker/bake-action@v3.1.0
      with:
        files: ./docker-compose.yml
        targets: ${{ matrix.target }}
        set: |
          *.output=type=docker,dest=/tmp/image-${{ matrix.target }}.tar
          *.cache-from=type=gha,scope=build-${{ matrix.target }}
          *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max
    - uses: actions/upload-artifact@v3
      with:
        name: docker-image-${{ matrix.target }}
        path: /tmp/image-${{ matrix.target }}.tar
        
  test-compose:
    name: Test / docker compose
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
        path: /tmp
    - name: Load docker image
      run: ls /tmp/docker-image-*/image-*.tar | xargs -L1 docker load --input
    - name: Start docker compose
      run: docker compose up -d
    - name: Wait 15s
      run: sleep 15
    - run: docker compose ps -a
    - run: docker compose logs
    - name: Verify docker containers are running
      run: docker inspect --format "{{.ID}} {{.Name}} {{.State.Status}} {{.RestartCount}}" $(docker compose ps -aq) | node .github/actions/docker-compose-status.js
    - name: Stop docker compose
      run: docker compose down

  test-kubernetes:
    name: Test / kubernetes
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
    - uses: actions/checkout@v4 
    - uses: actions/download-artifact@v3
      with:
        path: /tmp
    - uses: nolar/setup-k3d-k3s@v1
      with:
        version: v1.26
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Load docker image
      run: ls /tmp/docker-image-*/image-*.tar | xargs -L1 docker load --input
    - name: Import images into k3d
      run: k3d image import gw2me/web gw2me/database-migration
    - run: kubectl apply -k kubernetes/local
    - run: kubectl rollout status deployment web database -n gw2me --timeout=120s
    - run: kubectl get deployment -n gw2me
      if: success() || failure()
    - run: kubectl get job -n gw2me
      if: success() || failure()
    - run: kubectl logs -l app.kubernetes.io/part-of=gw2me -n gw2me --all-containers --ignore-errors
      if: failure() || runner.debug == '1'
      
  success:
    name: Success
    needs: [build-node, lint, test-compose, test-kubernetes]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
    - run: exit 0


  publish-docker:
    name: Publish / Docker / ${{ matrix.target }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [success]
    strategy:
      matrix:
        target: [ web, database-migration ]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: docker-image-${{ matrix.target }}
        path: /tmp
    - name: Load docker image
      run: docker load --input /tmp/image-${{ matrix.target }}.tar
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image  
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}/${{ matrix.target }}
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag gw2me/${{ matrix.target }} $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION

  publish-npm:
    name: Publish / npm / ${{ matrix.target }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [success]    
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        target: [ api ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: npm
        registry-url: 'https://registry.npmjs.org'
    - name: Install latest npm
      run: |
        npm install --global npm@latest
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Run Publish
      run: npm run publish-package -- --filter=${{ matrix.target }}...
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_CONFIG_PROVENANCE: true
