name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build / Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: npm
    - run: npm i -g npm@8.19.4
    - name: Install dependencies
      run: npm ci
    - name: Cache turbo
      uses: actions/cache@v3
      with:
        path: ./node_modules/.cache/turbo
        key: turbo-cache-build-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-cache-build-${{ runner.os }}-
    - name: Run Build
      run: npm run build -- --no-cache

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Cache turbo
      uses: actions/cache@v3
      with:
        path: ./node_modules/.cache/turbo
        key: turbo-cache-lint-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-cache-lint-${{ runner.os }}-
    - name: Run Lint
      run: npm run lint

  success:
    name: Success
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
    - run: echo "Success"
